### ISSUE TITLE
python Run Code有一些问题

### ISSUE THREAD

**Issue by sowhatmelon** [spencerwooo/dowww#12]
![2019-01-11 161421](https://user-images.githubusercontent.com/46592005/51022063-2e85c900-15be-11e9-8a56-188ffe2dcb51.jpg)
大佬，我按照教程配置好后，run code这样提示，要手动改成python3才行，请问怎么解决
![2019-01-11 161633](https://user-images.githubusercontent.com/46592005/51022065-2e85c900-15be-11e9-9fb0-fe5e99563360.jpg)

**Comment by spencerwooo** [comment]
试试在 Code Runner 的配置项里面把 Python 模块的那个运行指令换一下？比如：

```json
"code-runner.executorMap": {
  "python": "python3 -u"
}
```

**Comment by sowhatmelon** [comment]
啊！可以了，谢谢！
