### ISSUE TITLE
VScode配置中文

### ISSUE THREAD

**Issue by wuhang2003** [spencerwooo/dowww#13]
🤔 **我在这个页面的配置过程遇到了问题！**

> 详细说说你在配置哪一部分遇到了问题，有页面链接更好啦！

🎉 **我觉得这里可以这样改进！**
论VScode如何配置中文
在插件商店搜索Chinese，第一个是简体中文，第二个是繁体中文
或者也可以去这里[Chinese (Simplified) Language Pack for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans)
安装插件，重启VScode
Enjoy Chinese！
> 附上链接，我即刻更新！

💡 **一个新的 Idea！**

> 详细讲讲，可以直接 PR！欢迎欢迎！

**Comment by spencerwooo** [comment]
设置语言等问题属于基础配置项了，不在这里做过多介绍了。
