### ISSUE TITLE
出现黑色三角

### ISSUE THREAD

**Issue by xianzheTM** [spencerwooo/dowww#14]
大佬，请问为什么Terminus中一直有个黑色三角去不掉
![default](https://user-images.githubusercontent.com/25103583/51370161-18818680-1b31-11e9-940a-462e3d04b9ce.png)
我已经安装了powerline字体，其余设置是按照你的文档里设置的，启用的是powerlevel9k主题

**Comment by spencerwooo** [comment]
对，确实有这个问题。这个算是个 Fluent 设计的一个问题吧。

命令里面出现那个黑色三角是因为，它为了让前景颜色（Foreground Color）和背景（Background Color）一样，将前景颜色设置为黑色。但是背景颜色可以渲染为那个 Fluent 设计的透明颜色而前景没法这样渲染就只能渲染成黑色。你可以把前面那部分的颜色改成除了黑色外的颜色，比如前面那部分是 context，你就可以在 `.zshrc` 里面加上 `POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="cyan"` 或者类似的配置，可以自己摸索一下。

<img width="714" alt="applicationframehost_cmnfhvpnls" src="https://user-images.githubusercontent.com/32114380/51370865-8038d100-1b33-11e9-8f52-bc165e401905.png">

然后标签页（Tab）上面那个好像是 bug，我也没改明白...不如去 Terminus 那提 Issue？

**Comment by xianzheTM** [comment]
谢谢你的回复，我明白问题出在哪里了。现在出现另一个小问题
![default](https://user-images.githubusercontent.com/25103583/51373107-356e8780-1b3a-11e9-8970-ce0b9d0cb86c.png)

我直接模仿了你的zsh配置文件，出现上图的问题，请问是我漏掉了什么字体吗？
谢谢😀

**Comment by spencerwooo** [comment]
`POWERLEVEL9K_MODE=nerdfont-complete`

可能是差一个这个配置？

我用的是 Nerd Fonts：<https://github.com/ryanoasis/nerd-fonts>

**Comment by xianzheTM** [comment]
我在Windows和wsl中都分别安装了这个字体系列，但是仍旧没出现预期的效果，这是WSL的效果：
![default](https://user-images.githubusercontent.com/25103583/51389670-053ddd80-1b68-11e9-8aad-43f0ef1a45a9.png)
Terminus中字体设置为Iosevka Nerd Font
请问还有没有什么认为我配置错误的地方？
谢谢

**Comment by xianzheTM** [comment]
好吧，谢谢帮助。👍
