### ISSUE TITLE
Windows的默认终端conhost.exe

### ISSUE THREAD

**Issue by 12101111** [spencerwooo/dowww#16]
🎉 我觉得这里可以这样改进！

> Terminal，即「终端模拟器」。我们需要一个终端去和我们的 shell 进行交互。2018 年马上就要过去了，Windows 的自带终端依旧不支持 256 色彩

Windows的默认终端是支持24位色的,命令行程序使用conpty即可输出24位色

https://github.com/bitcrazed/24bit-color

这个仓库是2年前Windows Console和WSL开发者用来测试24位色输出的

效果图

![image](https://user-images.githubusercontent.com/8438475/51588608-aee1ed80-1f1f-11e9-98e7-93903fe86666.png)

https://github.com/Microsoft/console

这个仓库不仅能反馈Windows控制台issue,还包括了一个C++一个C#如何使用conpty的样例程序,以及最重要的,有一个更改Windows控制台配送方案的工具,可以使用iterm2的主题.

有必要加入原生终端的配置说明,毕竟conhost远快于electron.

**Comment by spencerwooo** [comment]
这部分我更新了一些内容：[默认的 WSL 终端模拟器](https://spencerwoo.com/dowww/2-Toolchain/2-1-TerminalEnv.html#%E7%BB%88%E7%AB%AF-terminal)，不知道有没有讲全。如果您还有补充的地方，欢迎直接 PR，毕竟只提 issue 没办法直接算在 Contributor 里面。

**Comment by 12101111** [comment]
字体暂时没有更好的解决方案.很多等宽字体在显示特殊全角符号后光标就会错位.
https://github.com/Microsoft/console/issues/353
在这方面浏览器排版引擎做的更好

**Comment by spencerwooo** [comment]
@12101111 了解了，感谢~ 这里您还有补充的内容吗？没有的话我就把这个 issue 关掉了
