### ISSUE TITLE
🚀 为什么在 WSL 下项目的编译/运行/git 等等和 IO 相关的操作貌似很慢？

### ISSUE THREAD

**Issue by xiaok** [spencerwooo/dowww#17]
🤔 **我在这个页面的配置过程遇到了问题！**

代码放在 /mnt/c/shared 目录下，使用 windows 的 vscode 进行开发
代码在 wsl 中编译，运行
中型项目，巨慢无比，有没有办法缓解IO问题呢？

**Comment by spencerwooo** [comment]
这是个大问题，基本上没有方法。WSL 的 IO 就是一如既往的慢，这是个已知的问题，可以看：

- [git status slow on DrvFS](https://github.com/Microsoft/WSL/issues/981)
- [Major performance (I/O?) issue in /mnt/* and in ~ (home)](https://github.com/Microsoft/WSL/issues/873)

这两个 issue 里面的描述，基本上是微软在努力解决了，但是还是距离原生的 Linux 有很大的差距。

**Comment by spencerwooo** [comment]
对了，可以试试把 Windows 的实时监控关闭（Disable REALTIME protection in Windows Defender），这样可能对性能有提升。详细见 > [Windows Defender/Anti-malware Causing Performance Issues after CU update](https://github.com/Microsoft/WSL/issues/1932)

**Comment by spencerwooo** [comment]
@llinfeng 这个就很有意思了。

- 实时监控：我觉得关掉实时监控对我自己来说还是有挺大影响的，因为我自己电脑还是依赖 Windows Defender 防御入侵的，所以心里还是会觉得不安全。
- 添加 exception：读到有人说没有任何用处，就也很懵，我自己还是把工作文件夹放到白名单里面了的，不过其实也没有特别的性能提升。

后边你提到的那个方法我不知道有没有作用...我也没试过。

**Comment by llinfeng** [comment]
[LxRunOffline](https://github.com/DDoSolitary/LxRunOffline)老厉害了，找到合适的image之后，基本一键compile新系统。更棒的是，root所在的folder能找到，也能挪来挪去——逼急了都可以搞到U盘上。
@spencerwooo 要不你在这个repo的合适地方，加一个空白的`*.md`文件，我来改吧改吧先推上去

**Comment by spencerwooo** [comment]
@llinfeng 感谢，我已经在 `./docs/4-Advanced` 下建了一个叫 `4-2-LxRunOffline.md` 的文件，欢迎大佬发挥。贡献规范和项目的本地构建方式还请参考 > [参与贡献](https://github.com/spencerwooo/dowww/blob/master/.github/CONTRIBUTING.md) 🌹

**Comment by xiaok** [comment]
亲测：
把实时监控整个关掉，有效果，但是还是慢
把项目文件加入忽略，没有可见的效果

另外，nvm, zsh 会极大极大的拖慢 IO 速度，我用的是surface pro，性能本就不咋地，装了nvm zsh等软件后慢到无法忍受，现在用原生bash只能说勉强能用

**Comment by spencerwooo** [comment]
不知道大家有没有了解 WSL 2，如果没有请看这篇官方博客：[Announcing WSL 2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/).

总之，针对文件系统 I/O 性能问题，WSL 2 为 WSL 带来了「革命性的文件系统性能提升」。

> Changes in this new architecture will allow for: dramatic file system performance increases, and full system call compatibility, meaning you can run more Linux apps in WSL 2 such as Docker.

可以期待一下。

**Comment by llinfeng** [comment]
关于提升WSL速度——https://gist.github.com/noelbundick/9c804a710eb76e1d6a234b14abf42a52，把`*.ps1`文本执行一下就好了。

关于WSL2：就算把Windows系统更新到Build 1903，也要等到六月底，需要WSL2在Windows Store上架了才能有的用。

**Comment by TheBegining** [comment]
使用过 WSL2，用来做React Typescript开发。
![image](https://user-images.githubusercontent.com/17702287/65006041-82f2fc80-d934-11e9-989e-c9c3bf2f568f.png)
但是体验并不好，如果文件放在 `/mnt/c` 里面，编译，和类型检查 速度相当的慢。
直接放在`~/` 会好很多，会快大概一分多钟吧。

**Comment by spencerwooo** [comment]
@TheBegining 是这样的，WSL 2 速度上的优势就体现在将文件直接放在 Linux 目录下时的体验。如果放在 Windows 目录下，跟原来的就差不多。

**Comment by spencerwooo** [comment]
WSL 2 发布之后，我觉得该问题已经解决。详见：[准备工作 - WSL 2 中采用的新措施](https://dowww.spencerwoo.com/1.0/1-Preparations/1-0-Intro.html#wsl-2-%E4%B8%AD%E9%87%87%E7%94%A8%E7%9A%84%E6%96%B0%E6%8E%AA%E6%96%BD)。Closed.

**Comment by llinfeng** [comment]
WSL 2目前也不一定是万灵药——我在台式机和T480笔记本上分别用Windows Insider (Slow Channel) 装上了WSL 2。T480一下就整个操作系统慢慢的+启动WSL 2超慢的；台式机却还没怂。

总的来说，**Windows系统也该有各种坑**——问Lenovo Support的客服，说自己的Windows OS是optimized for T480的。用户自己随便乱升级Windows OS是会自讨苦吃的。

-----

有条件的话（家用路由器该就够用），一台老电脑刷个Linux系统（Linux Mint ）也是个不错的解决办法——我基本就放弃优化WSL中间事情了。用SSH+X11，能连到身边局域网里面的老机器就够用了。
