### ISSUE TITLE
Terminus 终端使用 Iosevka Nerd Font 字体无法显示 PowerLine 图标

### ISSUE THREAD

**Issue by wuhang2003** [spencerwooo/dowww#19]
🤔 **我在这个页面的配置过程遇到了问题！**

> 我已经安装好 Iosevka Nerd Font 这个字体了，在字体设置也选择了这个字体，但是我开启 WSL 终端时字体无法显示出来，请求帮助
 

![snipaste_2019-01-24_10-54-26](https://user-images.githubusercontent.com/17929366/51651484-0c7d4500-1fc7-11e9-9f74-d87e24ba3fee.png)
![snipaste_2019-01-24_10-54-46](https://user-images.githubusercontent.com/17929366/51651486-0d15db80-1fc7-11e9-9216-52b423c965f6.png)

🎉 **我觉得这里可以这样改进！**

> 附上链接，我即刻更新！

💡 **一个新的 Idea！**

> 详细讲讲，可以直接 PR！欢迎欢迎！

**Comment by spencerwooo** [comment]
Font 那里，你试试改成 Iosevka，把后面的 Nerd Font 删掉。我之前安装的时候，Iosevka 的识别名就是 Iosevka，没有后面的 Nerd Font。你这里的设置就直接没有识别出这个字体。

**Comment by wuhang2003** [comment]
感谢作者，问题已解决
