### ISSUE TITLE
Python WSL Port

### ISSUE THREAD

**Issue by c4dr01d** [spencerwooo/dowww#20]
🤔 **我在这个页面的配置过程遇到了问题！**
Python配置vscode时
> 详细说说你在配置哪一部分遇到了问题，有页面链接更好啦！
配置完了解释器，pylint，autopep8之后，尝试运行解释器时报错
🎉 **我觉得这里可以这样改进！**
wsl内需要将windows下的路径转为wsl的路径，而不是Windows的路径
> 附上链接，我即刻更新！
https://spencerwoo.com/dowww/3-VSCode/3-3-Python.html#让-vscode-集成-wsl-侧-python
💡 **一个新的 Idea！**

> 详细讲讲，可以直接 PR！欢迎欢迎！

**Comment by spencerwooo** [comment]
具体错误长什么样子啊？我没太看明白，是没识别到 `python` 或是 `python3` 吗？

**Comment by c4dr01d** [comment]
不是，你写的教程，路径是写的windows下工具的路径，现在vscode可以直接识别wsl里面的路径，即`python.pythonPath`可以设为`/usr/bin/python`或`/usr/bin/python3`了

**Comment by spencerwooo** [comment]
是预览版的 VSCode 吗？我这里还不能这样设置，会报错。

<img width="524" alt="code_8ku6jm5f3g" src="https://user-images.githubusercontent.com/32114380/52340671-55171280-2a4b-11e9-9ee3-9b0cc2c1dd6a.png">

**Comment by c4dr01d** [comment]
我这是正式版，你可能需要更新一下vscode

**Comment by spencerwooo** [comment]
<img width="304" alt="code_xs9oznzg0p" src="https://user-images.githubusercontent.com/32114380/52340902-0322bc80-2a4c-11e9-9c67-cf695401fbb2.png">

Nope... 最新版，没有更新。

官方有讲这个事情吗？目前我就看到探索 WSL 支持的这个提上日程，没有具体讲怎么直接这样设置。

**Comment by c4dr01d** [comment]
我的是可以的，我直接设置的`terminal.integrated.shell.windows`和`git.path`是Windows路径，其它的都是Linux路径。
``` json
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\wsl.exe",
"git.path": "D:\\Tools\\wslgit.exe"
```

**Comment by c4dr01d** [comment]
其它的路径我都设置的是Linux的

**Comment by spencerwooo** [comment]
我有时间研究一下，这个我自己能复现再更新。如果有官方的更新日志、配置教程或者相关的 GitHub Issue 麻烦附在这里吧，辛苦❤️

**Comment by c4dr01d** [comment]
我已经给了QwQ

**Comment by spencerwooo** [comment]
啊？？？没看懂。。。哪里有链接啊？

**Comment by c4dr01d** [comment]
你没看到我前面刚刚给的json代码吗？我给了Windows的，Linux形式的路径配置我没给

**Comment by spencerwooo** [comment]
不是，你的意思是就是现在 VSCode 的 Python 插件已经支持直接识别 WSL 下的 Python 路径不是吗？就是说现在我可以直接这样配置：

```json
"python.pythonPath": "/usr/bin/python",
"python.linting.pylintPath": "/usr/bin/pylint",
...
```

然后 `git` 的路径还是需要用 `wslgit` 转一下，内嵌终端的路径直接指向 `wsl.exe`，这样 Python 插件就可以直接用 WSL 里面的 `python` 了对吧？我这个没理解错吧？

我的意思是我现在这样配置 VSCode 还是识别不了 `python` 和 `pylint`，然后我也没在官方的插件库 
issue 里面找到相应的更新说明，WSL 的 issue 下面也没说这回事，我自己没办法复现啊，所以就这样...

**Comment by c4dr01d** [comment]
嗯，你理解的没错

**Comment by c4dr01d** [comment]
但是我的可以用

**Comment by spencerwooo** [comment]
行，我有时间研究一下这个。毕竟如果能这样配置就很方便了

**Comment by c4dr01d** [comment]
嗯，反正我的可以/斜眼笑

**Comment by wilkice** [comment]
> 行，我有时间研究一下这个。毕竟如果能这样配置就很方便了

试了半天，我的也不行，VS code version `1.31.1`, WSL 18.04

**Comment by spencerwooo** [comment]
Stale, closed.
