### ISSUE TITLE
wsl-open无法打开windows资源管理器

### ISSUE THREAD

**Issue by pk49800** [spencerwooo/dowww#24]
🤔 **我在这个页面的配置过程遇到了问题！**
https://spencerwoo.com/dowww/2-Toolchain/2-2-DevTools.html#wsl-open
按照教程安装好wsl-open后尝试打开windows上面的c盘遇到如下错误提示：

/mnt# ls -a
.  ..  c  d  e  g  h  i  j
/mnt# wsl-open /mnt/c/
/usr/local/bin/wsl-open: line 227: powershell.exe: command not found
exit 127

**Comment by spencerwooo** [comment]
试试直接进入 C 盘然后再使用 `wsl-open`，即：

```bash
cd /mnt/c
wsl-open .
```

当然，我看你报错信息是找不到 `powershell.exe` 路径，所以如果上面不行的话再试试：

```bash
cd /mnt/c
explorer.exe .
```

**Comment by pk49800** [comment]
按照你的提示来也不行
[sudo] password for pk49800:
~# cd /mnt/c
/mnt/c# wsl-open .
/usr/local/bin/wsl-open: line 227: powershell.exe: command not found
exit 127
/mnt/c# explorer.exe
zsh: command not found: explorer.exe
exit 127
/mnt/c#

**Comment by spencerwooo** [comment]
为什么有 `sudo`？你能在 WSL 环境下唤起 PowerShell 吗？

**Comment by pk49800** [comment]
sudo那一句是我输入root密码切换到root环境的，WSL环境也没法唤起powershell
/mnt/c/Windows/System32/WindowsPowerShell/v1.0# powershell.exe
zsh: command not found: powershell.exe
exit 127
/mnt/c/Windows/System32/WindowsPowerShell/v1.0# wsl-open powershell.exe
/usr/local/bin/wsl-open: line 227: powershell.exe: command not found
exit 127

**Comment by spencerwooo** [comment]
不知道这个问题怎么解决了。。。

**Comment by pk49800** [comment]
我无法在wsl里面运行exe应用程序

**Comment by spencerwooo** [comment]
Stale, closed.
