### ISSUE TITLE
VSCode使用Python插件的错误提示

### ISSUE THREAD

**Issue by pk49800** [spencerwooo/dowww#25]
🤔 **我在这个页面的配置过程遇到了问题！**

按照教程一步步来配置好了Python环境，使用上似乎没问题，不过每次打开VSCODE总是跳出Python扩展未安装的错误提示：

Python is not installed. Please download and install Python before using the extension.
![image](https://user-images.githubusercontent.com/36910388/56258760-4744d400-6103-11e9-9b7b-9bf361f2bad6.png)

**Comment by spencerwooo** [comment]
玄学问题，忽略即可。等待 Python 官方插件完善就好了。
