### ISSUE TITLE
我在配置vscode的c++环境时,编译报错的文件目录是错误的

### ISSUE THREAD

**Issue by lyy4758** [spencerwooo/dowww#26]
编译之后的提示是这样的,这是哪里配置的问题呢?报错目录重复了
![image](https://user-images.githubusercontent.com/29500263/56480135-55bc3280-64eb-11e9-9a20-f9859021ec07.png)

**Comment by spencerwooo** [comment]
这是你自己目录配置问题（如果我没看错的话应该是 `tasks.json` 写的问题），在 WSL 中目录是以 `/mnt/f` 开头的，你这里配置的依旧是 Windows 下路径，所以 VS Code 才找不到相应的文件。

**Comment by lyy4758** [comment]
> 这是你自己目录配置问题（如果我没看错的话应该是 `tasks.json` 写的问题），在 WSL 中目录是以 `/mnt/f` 开头的，你这里配置的依旧是 Windows 下路径，所以 VS Code 才找不到相应的文件。

![Uploading image.png…]()
这是我的tasks.json的配置,我只改了/mnt/f的位置

**Comment by spencerwooo** [comment]
不知道。实在不行就试试这个吧：<https://marketplace.visualstudio.com/items?itemName=lfurzewaddock.vscode-wsl-workspacefolder>。

**Comment by lyy4758** [comment]
好的,我试试看吧
