### ISSUE TITLE
LaTeX 配置之后 SyncTeX 无法正常工作

### ISSUE THREAD

**Issue by zhhhhxhq** [spencerwooo/dowww#27]
SyncTeX 需要使用文件的绝对路径，这样的话将编译器换成 wsl 后导致 LaTeX-Workshop 的 SyncTeX 功能无法使用。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by spencerwooo** [comment]
@patrick330602 大佬来看看？

**Comment by patrick330602** [comment]
试试这个解决方法？https://github.com/James-Yu/LaTeX-Workshop/issues/460

**Comment by spencerwooo** [comment]
@zhhhhxhq 如果你问题有所解决的话请来说一下啊 ~ 我手头没有 Windows 电脑，没办法验证这个问题

**Comment by zhhhhxhq** [comment]
>@zhhhhxhq 如果你问题有所解决的话请来说一下啊 ~ 我手头没有 Windows 电脑，没办法验证这个问题

@spencerwooo 没有看懂 @patrick330602 给出的方法。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patrick330602** [comment]
解决方法是这个：https://github.com/James-Yu/LaTeX-Workshop/issues/460#issuecomment-440639823

准确来说是将命令放在单独的 sh 文件里（build.sh, 文件部分可以用`"$(pwd)"/"$@" 包装起来`）用bat文件包装起来，然后 build 时用这个 batch 文件。这个是个 workaround，插件作者似乎没修这个 bug

**Comment by zhhhhxhq** [comment]
试了一下还是不太行，最近比较忙，没有时间折腾这个了。

**Comment by zhhhhxhq** [comment]
VS Code 新推出的 [Remote-WSL](https://code.visualstudio.com/docs/remote/wsl) 完美解决了这个问题。
