### ISSUE TITLE
官方已经支持了WSL远程开发环境

### ISSUE THREAD

**Issue by redblue9771** [spencerwooo/dowww#28]
💡 **发来贺电**

*官方已经宣布支持在Windows下使用WSL开发环境https://code.visualstudio.com/docs/remote/wsl#_getting-started*
相同的还有docker、ssh
准备好更新**dowww**了吗
...

**Comment by spencerwooo** [comment]
等正式版上线我就更新！现在只有 Insiders 版本能安装，稍安勿躁。❤️
