### ISSUE TITLE
💡 Remote-WSL 的更新

### ISSUE THREAD

**Issue by spencerwooo** [spencerwooo/dowww#29]
日前 Remote-WSL 插件已经更新，WSL 开发环境正式被 VS Code 支持。目前 `Dev on Windows with WSL` 我本人仅仅更新了一些 [体验和使用特性](https://spencerwoo.com/dowww/3-VSCode/#remote-wsl-%E6%8F%92%E4%BB%B6)，希望有更多同学帮助我完善。在这里给大家拜年了 ♥

**Comment by black-desk** [comment]
![image](https://user-images.githubusercontent.com/29726878/57971413-4cc26200-79c0-11e9-97ab-207d1f59b23b.png)
实测这样设置zsh以后可以正常使用

**Comment by spencerwooo** [comment]
@black-desk 讲道理我在 WSL 里面设置了默认 Shell 它打开的就应该是，不需要再在 VS Code 里面单独配置一下了啊。所以我觉得这个确实是个 bug。

**Comment by black-desk** [comment]
@spencerwooo 你试着这样理解，把wsl当作一个虚拟机，那么在vsc这里调用终端相当于是在这个虚拟机里执行一个程序，这个选项的值默认是/bin/bash，在windows下执行wsl.exe确实是打开的已经配置过的zsh终端，但是在wsl内部打开/bin/bash的时候执行的还是bash啊
