### ISSUE TITLE
Terminus 无法改变终端的主题

### ISSUE THREAD

**Issue by TZTsai** [spencerwooo/dowww#33]
🤔 **我在这个页面的配置过程遇到了问题！**
我直接在bash里运行source ~/.zshrc的时候没有问题，然而在terminus里运行的时候就提示错误
![image](https://user-images.githubusercontent.com/34415979/58363793-6f7eda00-7edc-11e9-8bbe-d18b9ac0de40.png)

**Comment by spencerwooo** [comment]
@TZTsai 这个是提醒你没有安装 autoload 吧？安装一下就好了？

**Comment by TZTsai** [comment]
不是，就没有autoload这个安装包...

**Comment by spencerwooo** [comment]
这里也有这个问题：https://github.com/robbyrussell/oh-my-zsh/issues/6405

看样子重新安装，然后把默认 Shell 设置为 zsh 就可以了

**Comment by zhaoyou** [comment]
chsh -s /bin/zsh
