### ISSUE TITLE
请教一些WSL下使用GUI的报错与警告

### ISSUE THREAD

**Issue by chuyunduan** [spencerwooo/dowww#34]
本人是liuux的初学者，因为下学期要学习有关操作系统的知识，本人也是软粉一个。所以当我刚知道WSL的存在的时候就迫不及待地准备上手了。因为是新手，所以更偏向于用GUI界面，现在的的用的是从商店直接下载的ubuntu，版本号是18.04。看了不少博客教程后借助VcXsrv,GUI已经能够运行，桌面环境是gnome，但是还存在一些报错和警告，因为初学很多东西看不懂，而且网上相关的中文论坛也比较少，有幸发现**Dev on Windows with WSL**项目。准备日后在使用过程中贴出来一些出现的报错与警告，求助解答之余希望也能帮助到有同样困惑的人。
第一次接触github，可能会做出一些不符合github约定成俗的行为，在这里先道一声抱歉，同时希望大佬们能指点使用GitHub的正确姿势，多谢。
下面开始放问题。

**Comment by chuyunduan** [comment]
本人是liuux的初学者，因为下学期要学习有关操作系统的知识，本人也是软粉一个。所以当我刚知道WSL的存在的时候就迫不及待地准备上手了。因为是新手，所以更偏向于用GUI界面，现在的的用的是从商店直接下载的ubuntu，版本号是18.04。看了不少博客教程后借助VcXsrv,GUI已经能够运行，桌面环境是gnome，但是还存在一些报错和警告，因为初学很多东西看不懂，而且网上相关的中文论坛也比较少，有幸发现Dev on Windows with WSL项目。准备日后在使用过程中贴出来一些使用过程中的报错与警告，求助解答之余希望也能帮助到有同样困惑的人。
第一次接触github，可能使用中做出一些不符合github约定成俗的行为，在这里先道一声抱歉，同时希望大佬们能告诉我应该怎样正确使用github，多谢。

**Comment by chuyunduan** [comment]
桌面环境启动后bash出现的一些警告

`** (update-notifier:604): WARNING **: 09:27:57.990: not starting for system

06:28:01:0761 Gs  plugin appstream took 2.3 seconds to do setup

06:28:01:0788 Gs  enabled plugins: desktop-categories, fwupd, os-release, packagekit-local, packagekit-offline, packagekit-proxy, packagekit-refine-repos, packagekit-refresh, packagekit-upgrade, packagekit-url-to-app, packagekit, shell-extensions, systemd-updates, ubuntuone, appstream, desktop-menu-path, flatpak, generic-updates, hardcoded-blacklist, hardcoded-featured, hardcoded-popular, modalias, packagekit-refine, rewrite-resource, steam, odrs, packagekit-history, provenance, icons, provenance-license, key-colors, key-colors-metadata

06:28:01:0790 Gs  disabled plugins: dpkg, dummy, repos, epiphany, snap

06:28:02:0013 PK  failed to set proxy:GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_2dengine_2derror_2dquark.Code3: setting the proxy failed: failed to get the session

06:28:02:0015 GsPluginPackageKit failed to set proxies: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_2dengine_2derror_2dquark.Code3: setting the proxy failed: failed to get the session

06:28:03:0056 Gs  failed to call gs_plugin_refresh on fwupd: invalid handle

06:28:03:0845 Gs  hiding category games featured applications: found only 0 to show, need at least 9

06:28:03:0847 Gs  hiding category productivity featured applications: found only 0 to show, need at least 9

06:28:03:0848 Gs  Only 0 apps for recent list, hiding

06:28:05:0217 Gs  Only 8 apps for popular list, hiding

06:28:28:0886 GsPluginPackageKit Failed to find one package for byobu.desktop, /usr/share/applications/byobu.desktop, [0] `

**Comment by chuyunduan** [comment]
第二个问题，火狐浏览器安装插件永远是installing，进度条一点也不动。

**Comment by spencerwooo** [comment]
针对你上面提到的两个问题：

1. 开启 GUI 出现的「警告」应该是 Log（即：日志），可以忽略，只要桌面环境打开正常就可以。
2. 火狐插件永远 Installing 跟你的网络环境有关，和 WSL 本身无关。（可能需要科学上网）

PS：
- 并不是很建议直接通过 WSL 开启图形界面环境，反而直接在你的电脑上安装另外一个 Linux 系统来学习 Linux 的体验更佳。
- 当你熟练掌握 Linux 基础命令之后，通过 WSL 进行操作系统课程的相关实验会更佳方便。

**Comment by chuyunduan** [comment]
感谢您的回复，人再国外，各种网络服务一切正常，应该不是网络问题。如果有时间麻烦帮忙看一下，谢谢。

发送自 Windows 10 版邮件应用

发件人: Spencer Woo
发送时间: 2019年6月2日 8:25
收件人: spencerwooo/dowww
抄送: chuyunduan; Author
主题: Re: [spencerwooo/dowww] 请教一些WSL下使用GUI的报错与警告 (#34)

针对你上面提到的两个问题：
1. 开启 GUI 出现的「警告」应该是 Log（即：日志），可以忽略，只要桌面环境打开正常就可以。
2. 火狐插件永远 Installing 跟你的网络环境有关，和 WSL 本身无关。（可能需要科学上网）
PS：
• 并不是很建议直接通过 WSL 开启图形界面环境，反而直接在你的电脑上安装另外一个 Linux 系统来学习 Linux 的体验更佳。
• 当你熟练掌握 Linux 基础命令之后，通过 WSL 进行操作系统课程的相关实验会更佳方便。
