### ISSUE TITLE
配置zsh后vscode-insiders终端依然是bash

### ISSUE THREAD

**Issue by greatshieh** [spencerwooo/dowww#35]
根据[集成终端使用wsl](https://spencerwoo.com/dowww/3-VSCode/3-0-Terminal.html#配置)进行了配置，并且[默认shell环境配置为zsh](https://spencerwoo.com/dowww/2-Toolchain/2-1-TerminalEnv.html#配置-zsh)，从wsl.exe可以直接进入zsh, 但是启动vscode-insiders后，终端环境还是bash。

vscode-insiders: 1.35.6
Remote-WSL: 0.36.0

**Comment by spencerwooo** [comment]
已知问题，等正式版发布再说吧。

**Comment by spencerwooo** [comment]
这里我也提到了这一问题：[VS Code | 默认的 WSL 终端](https://spencerwoo.com/dowww/3-VSCode/#%E9%BB%98%E8%AE%A4%E7%9A%84-wsl-%E7%BB%88%E7%AB%AF)

**Comment by greatshieh** [comment]
在setting文件中，除设置windows环境下的集成终端外，再设置一下linux环境下的集成终端。
` "terminal.integrated.shell.linux": "/usr/bin/zsh",`
再打开vscode-insiders就是zsh了。

**Comment by spencerwooo** [comment]
Stable 版本 VS Code 里面安装的 Remote-WSL 插件已经不会触发这个问题了，也不需要特殊配置 VS Code 设置项目。望周知。
