### ISSUE TITLE
pip安装参数

### ISSUE THREAD

**Issue by adong77** [spencerwooo/dowww#38]
🤔 **我在这个页面的配置过程遇到了问题！**
https://spencerwoo.com/dowww/3-VSCode/3-3-Python.html#%E5%AE%89%E8%A3%85-python
python -u pip install pylint，这个参数"-u"改为"-m"安装成功。

**Comment by spencerwooo** [comment]
我统一改成 `pip install pylint` 吧，按照 [官方文档](https://pypi.org/project/pylint/) 来。
