### ISSUE TITLE
使用-pip-安装必要的代码优化工具

### ISSUE THREAD

**Issue by Bend1031** [spencerwooo/dowww#39]
🎉 **我觉得这里可以这样改进！**

[使用-pip-安装必要的代码优化工具](https://spencerwoo.com/dowww/3-VSCode/3-3-Python.html#%E4%BD%BF%E7%94%A8-pip-%E5%AE%89%E8%A3%85%E5%BF%85%E8%A6%81%E7%9A%84%E4%BB%A3%E7%A0%81%E4%BC%98%E5%8C%96%E5%B7%A5%E5%85%B7)

前面按照步骤来的,在安装 pylint 时提示没有pip,所以将pip换成pip3,安装成功.建议将
命令换成
```
pip3 install pylint
```
```
pip3 install autopep8
```

**Comment by spencerwooo** [comment]
感谢建议。不同 Linux 发行版对待 `pip` 具体命令不一样，比如我现在使用的 Arch Linux 就是 `pip` 而非 `pip3`，这里按照 [官方文档](https://pypi.org/project/pylint/) 进行描述，暂时不考虑更改命令。

![image](https://user-images.githubusercontent.com/32114380/61865441-ce28fa00-af05-11e9-9de9-b555b56c9573.png)
