### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by Lips7** [spencerwooo/dowww#41]
*请从下面的三个模块中选择一个，在省略号处清晰的说明一下你遇到的问题/你的想法，并将不需要的模块删除。*

🤔 **我在这个页面的配置过程遇到了问题！**

*详细说说你在配置哪一部分遇到了问题，有页面链接更好啦！请清楚地表达你的环境、配置的过程、你遇到的问题和相应的截图。*

win10 build 18950
wsl version 2

在powershell上使用wsl命令所进入的shell(usr/bin/zsh)，与VSCode WSL Remote所进入的shell(sh)，完全不同，导致有些命令只能在VSCode里使用，而在powershell中必须通过 bash命令进入bash，在使用zsh命令进入zsh，才能做到。
查遍google也没找到解决办法，十分苦恼啊。

**Comment by Lips7** [comment]
![image](https://user-images.githubusercontent.com/51849534/62350273-d9e37480-b534-11e9-9b4c-9cc7801f57ab.png)
![image](https://user-images.githubusercontent.com/51849534/62350348-0b5c4000-b535-11e9-87d8-1f7dc0e51a7b.png)

**Comment by spencerwooo** [comment]
你可以直接在 VS Code 里面指定开启的 Shell 为 `/usr/bin/zsh`，应该就可以统一 PowerShell `wsl` 命令和 VS Code 打开的 Shell 了。这样应该是比较方便的。

**Comment by Lips7** [comment]
设定过后也一样
执行`pstree`后得到结果如下
![image](https://user-images.githubusercontent.com/51849534/62530828-d2dd9e80-b873-11e9-9b01-89f19627d274.png)
分别执行`echo $PATH` 得到的环境变量也不同
在powershell里执行`wsl`后得到的环境变量**包含windows的环境变量**，但**不包含用户环境变量**，如`/home/lips/.local/bin`
remote-wsl里得到的环境变量正好相反，**不包含windows**，但**包含用户环境变量**

环境变量应该给某个脚本修改过，**不是wslServer.sh**，但也没找到。
btw更新到wsl 2后只能通过`\\wsl$\Ubuntu\`才能从windows访问wsl的文件系统（可以在wsl里执行`wslpath '/'`得到）

**Comment by spencerwooo** [comment]
我手头没有 Windows 电脑...没法复现这个问题。我也不太知道这个怎么解决...

**Comment by Lips7** [comment]
> 我手头没有 Windows 电脑...没法复现这个问题。我也不太知道这个怎么解决...

https://github.com/microsoft/WSL/issues/4374
被官方大佬回复了，说会很快解决。

**Comment by Lips7** [comment]
> 我手头没有 Windows 电脑...没法复现这个问题。我也不太知道这个怎么解决...

https://github.com/microsoft/WSL/issues/4374
官方大佬回复了，说会尽快解决。

**Comment by spencerwooo** [comment]
Amazing，解决了就好，等官方 PR 了~
