### ISSUE TITLE
Windows Terminal 白边

### ISSUE THREAD

**Issue by woxj** [spencerwooo/dowww#44]
对于windows terminal 选择dark主题的白边有没有更好的方式可以不显示？

现在的方法是设置Windows主题的颜色为黑色

版本是 0.8.10261.0

![Snipaste_2020-02-09_23-32-57](https://user-images.githubusercontent.com/53204626/74104957-a8f39480-4b94-11ea-82ac-ad7b0c3a4b7d.png)

猜测和显卡有关？有时候会突然卡顿，然后显示边框未全黑色的，重启就又是白边了

![Snipaste_2020-02-09_23-38-47](https://user-images.githubusercontent.com/53204626/74105171-6632bc00-4b96-11ea-81b5-5683dc9e54e6.png)

**Comment by spencerwooo** [comment]
白边是 by design，故意这样设计的，有关这个的讨论在 Windows Terminal 开发仓库已经有相关解释了，见 [Terminal has white borders in dark mode](https://github.com/microsoft/terminal/issues/3425)。目前解决方法只有给 Windows 主题颜色改成黑色。
