### ISSUE TITLE
WSL2配置GUI图形化窗口需要指定Windows系统的IP

### ISSUE THREAD

**Issue by lookingz** [spencerwooo/dowww#46]
[GUI图形化窗口](https://dowww.spencerwoo.com/dev/4-Advanced/4-1-GUI.html)在配置 WSL 参数时，如果使用的是WSL2，需要在配置中加入Windows的IP，如：
```sh
# 之前
echo 'export DISPLAY=:0.0' >> .profile
```

```sh
# 之后，替换your_windows_ip为Windows系统的IP
echo 'export DISPLAY=your_windows_ip:0.0' >> .profile
```

**Comment by spencerwooo** [comment]
Dev 分支已更改：[安装 XServer for windows - dev](https://dowww.spencerwoo.com/dev/4-Advanced/4-1-GUI.html#%E5%AE%89%E8%A3%85-xserver-for-windows)，感谢提供的修改建议。

![image](https://user-images.githubusercontent.com/32114380/75953616-b4fd1880-5eec-11ea-9596-28ee64b446d3.png)
