### ISSUE TITLE
关于WSL2代理配置的问题

### ISSUE THREAD

**Issue by Whale-fall** [spencerwooo/dowww#49]
WSL2更改了与宿主机的互作方式，已经不能通过localhost的方式访问，故代理的那一章节中设置127.0.0.1：端口号的方式已不再适用。
参见：[https://lengthmin.me/posts/wsl2-network-tricks/#%E4%B8%80%E4%B8%AA%E5%91%BD%E4%BB%A4](url)

**Comment by spencerwooo** [comment]
了解，欢迎 PR~

**Comment by spencerwooo** [comment]
Updated on latest commit.
