### ISSUE TITLE
Hyper 光标位置不对

### ISSUE THREAD

**Issue by kerHbal** [spencerwooo/dowww#5]
你好，按照这里 https://spencerwoo.com/dowww/2-Toolchain/2-1-TerminalEnv.html
终端环境配置完以后发现Hyper光标显示位置和实际位置不一样：
![2](https://user-images.githubusercontent.com/11629684/47796842-8620d200-dcfb-11e8-829a-2f585a9b1271.gif)
能看出是哪出问题了吗？谢谢

**Comment by spencerwooo** [comment]
这个是一个 `zsh-autosuggestion` 插件的问题，我也遇到了，目前不知道怎么解决，这个 Issue 我先开发着，遇到新的解决方法我也会在这里更新。

**Comment by kerHbal** [comment]
问题是我没有安装那个插件。。。本来不太确定有没有安，然后去文件夹 `~/.oh-my-zsh/custom/plugins` 里看了一下确实没有
![snipaste_2018-10-31_11-07-19](https://user-images.githubusercontent.com/11629684/47797755-4ce96180-dcfd-11e8-8eff-c6b0f3c5372f.png)

**Comment by spencerwooo** [comment]
看一下 `.zshrc` 里面的插件有没有，我不确定是不是这个的问题，因为这个空格问题时好时坏，我只是觉得是由于 `zsh-autosuggestions` 引起的，如果我有新的发现我也会更新在这里的。

**Comment by kerHbal** [comment]
我这也是时好时坏，`.zshrc` 里也没有
![snipaste_2018-10-31_11-23-51](https://user-images.githubusercontent.com/11629684/47798881-8753fe00-dcff-11e8-98b2-46d8ee85ca53.png)

**Comment by spencerwooo** [comment]
@kerHbal 这部分内容的解决方案我更新到文档的这里了 > [zsh & oh-my-zsh](https://spencerwoo.com/dowww/2-Toolchain/2-1-TerminalEnv.html#zsh-oh-my-zsh)，希望您有时间试一下这个方法有没有什么缺陷，我自己尝试是完美解决了。如果没有什么问题的话我就关掉这个 Issue 了~

**Comment by kerHbal** [comment]
@spencerwooo @printempw 多谢两位，我这也没问题了

**Comment by Whale-fall** [comment]
> 我使用 Hyper 时也出现过这个问题，这似乎是 Hyper 对于全角 Unicode 字符的支持不完善造成的。oh-my-zsh 的默认主题中的提示符中有个宽度为 2 个半角字符的 `➜` 字符（`~/.oh-my-zsh/themes/robbyrussell.zsh-theme`），我将其修改为 `>` 后光标位置就正常了。

好奇修改unicode是哪一项啊，不知道通过哪一项修改。
