### ISSUE TITLE
关于vscode终端的美化

### ISSUE THREAD

**Issue by Whale-fall** [spencerwooo/dowww#50]
有什么办法让vscode的终端应用terminal里的配色？以下是对比
wsl里的：
![Snipaste_2020-04-14_00-44-54](https://user-images.githubusercontent.com/22662209/79139665-4bc0cd00-7de9-11ea-8892-e2d8b1e613a2.png)
vscode里的：
![Snipaste_2020-04-14_00-43-59](https://user-images.githubusercontent.com/22662209/79139686-54b19e80-7de9-11ea-8323-9d499528b480.png)

**Comment by Whale-fall** [comment]
因为不会用PR，所以只能这么求助了QAQ

**Comment by spencerwooo** [comment]
Windows Terminal 的主题是自己的主题，VS Code 终端的配色是和 VS Code 自己的配色相匹配的。如果你想要将 VS Code 的终端用上 Windows Terminal 里的配色，那需要找到 VS Code 中可用的 Windows Terminal 主题，或者手动在 VS Code 里面根据 Windows Terminal 的配色方案进行单独的设置，详见：[Customizing a Color Theme](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme)。
