### ISSUE TITLE
在 WSL 中运行 exe 遇到权限问题

### ISSUE THREAD

**Issue by iChrAlpha** [spencerwooo/dowww#53]
*请从下面的三个模块中选择一个，在省略号处清晰的说明一下你遇到的问题/你的想法，并将不需要的模块删除。*

🤔 **我在这个页面的配置过程遇到了问题！**

近期阅读作者编写的 WSL 配置文档，感觉收获颇丰，首先非常感谢作者的辛勤付出！但……

[https://dowww.spencerwoo.com/1.1/2-CLI/2-3-Others.html#%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F](https://dowww.spencerwoo.com/1.1/2-CLI/2-3-Others.html#%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F)

这个页面中提到的 `explorer.exe` ，而我在运行的时候遇到权限问题：

```
xxx@xxxx ~  explorer.exe .
zsh: permission denied: explorer.exe 
```

换到 bash 也是如此：

```
 ✘ xxx@xxxx ~  bash
xxx@xxxx:~$ explorer.exe .
bash: /mnt/c/WINDOWS/explorer.exe: Permission denied
```

我试图 `cd` 到 `/mnt/c/Windows` 下使用 `chmod` 更改 `explorer.exe` 的操作权限，默认 `444` ，我试图更改到 `555` ，但是失败了

```
-r--r--r-- 2 xxxx xxxx 4483160 Apr 16 15:19  explorer.exe
```

还望作者不吝赐教，不胜感激！

目前使用 Windows 19041.207，微软商店提供的默认 Ubuntu ，配合 WSL 2

**Comment by spencerwooo** [comment]
目前我自己从来没遇到过类似的问题……简单搜索也没有发现特别有价值的解决方法，看看有没有别的大佬有遇到类似问题吧。

![image](https://user-images.githubusercontent.com/32114380/79533895-aab56900-80ab-11ea-962b-d182e12d9a11.png)

**Comment by Diffumist** [comment]
[如果配置过这个的话](https://dowww.spencerwoo.com/dev/2-cli/2-2-shell.html#%E5%A6%82%E6%9E%9C%E5%B8%8C%E6%9C%9B%E4%BB%8E%E6%A0%B9%E6%9C%AC%E4%B8%8A%E8%A7%A3%E5%86%B3-drvfs-%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F%E7%9A%84%E6%9D%83%E9%99%90%E9%97%AE%E9%A2%98) ，这里的文档可以修改一下，原来的挂载有权限问题
```
[automount]
enabled = true
root = /mnt/
options = "metadata,umask=22,fmask=111"
mountFsTab = true
```
改为
```
options = "metadata,umask=22,fmask=11"
```
应该就可以了（如果不是这个问题就溜了

**Comment by spencerwooo** [comment]
@iChrAlpha 解决了吗？用上面那个方法？

**Comment by Diffumist** [comment]
> @iChrAlpha 解决了吗？用上面那个方法？

帮你 @ 主账号 @ChrAlpha

**Comment by iChrAlpha** [comment]
> @ChrAlpha 解决了吗？用上面那个方法？

并未。

事实上，最初那个问题，在完全重装 WSL 后就消失了，但如果在 zsh 中 `source ~/.bashrc` 又能复现，即便再 `source ~/.zshrc` 也无济于事，不论挂载 opinions  `fmask=11` 还是 `fmask=111` 都是这样。

可以说是我手贱带来的问题吧。打扰了。
