### ISSUE TITLE
WSL 列出 Windows 文件颜色问题时，重启 WSL 的方式错误

### ISSUE THREAD

**Issue by zombie110year** [spencerwooo/dowww#55]
🎉 **我觉得这里可以这样改进！**

关闭 WSL 终端并不一定会导致 WSL 停止，正确的做法应该是退出 WSL 后，在 Windows 这边调用命令

```
wsl -t <发行版名>
```

来主动终止。发行版名可以通过 `wsl -l` 来查看。

https://dowww.spencerwoo.com/1.0/2-cli/2-2-shell.html#%E5%A6%82%E6%9E%9C%E5%B8%8C%E6%9C%9B%E4%BB%8E%E6%A0%B9%E6%9C%AC%E4%B8%8A%E8%A7%A3%E5%86%B3-drvfs-%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F%E7%9A%84%E6%9D%83%E9%99%90%E9%97%AE%E9%A2%98

**Comment by spencerwooo** [comment]
感谢建议，欢迎将改动 PR 到 `/dev` 文件夹下的文档里~
