### ISSUE TITLE
配置 vscode 在中文标点符号处断句

### ISSUE THREAD

**Issue by zombie110year** [spencerwooo/dowww#57]
💡 **一个新的 Idea！**

vscode 没办法给中文断词，导致在中文文档中 <kbd>Ctrl + 方向键</kbd> 很不方便，一按就跳一句。
可以设置 `editor.wordSeparators`，在里面加上中文常用的标点，这样在移动光标的时候会舒服点。

```js
    "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?、，。？！“”‘’；：（）「」【】〔〕『』〖〗",
```

不知道这个点子放到哪个话题比较合适。

**Comment by spencerwooo** [comment]
跟 WSL 没啥太大关系，就不放了吧。
