### ISSUE TITLE
更新到Windows Terminal Preview v0.11.1191.0后setting 的变化

### ISSUE THREAD

**Issue by Whale-fall** [spencerwooo/dowww#58]
原先的settting设置不再适用，如global设置，应按新版的特性重写:参照
[https://github.com/microsoft/terminal/issues/5458](url)

**Comment by spencerwooo** [comment]
谢谢建议，欢迎 PR~（文档里除了需要将 `requestedTheme` 改成 `theme` 貌似没有别的地方了吧？）

**Comment by Whale-fall** [comment]
hhh我也正在参照着改，暂时没有发现太大的区别。

**Comment by Whale-fall** [comment]
keybendings的写法有了变动，原来的格式不再正确；以及全局设置的位置需要变动

**Comment by Whale-fall** [comment]
以及好像不能通过profile的方式添加ssh了？这个格式错误我死活没调整过来
![Snipaste_2020-04-29_17-10-04](https://user-images.githubusercontent.com/22662209/80579253-4ba50c00-8a3c-11ea-8081-cb4757040ec0.png)

**Comment by Whale-fall** [comment]
找到原因了，好像profile只能添加5个了，不知道是不是这个原因

**Comment by spencerwooo** [comment]
> 找到原因了，好像profile只能添加5个了，不知道是不是这个原因

我可以加 6 个啊？版本是 `0.11.1121.0`。

![image](https://user-images.githubusercontent.com/32114380/80587324-ec012d80-8a48-11ea-8b9a-23830fdba9d1.png)

**Comment by Whale-fall** [comment]
91好像不一样 21的我昨天安装的,是可以6个的


 
---原始邮件---
发件人: "Spencer Woo"<notifications@github.com&gt;
发送时间: 2020年4月29日 18:41:56
收件人: "spencerwooo/dowww"<dowww@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Whale-fall"<1063558626@qq.com&gt;;
主题: Re: [spencerwooo/dowww] 更新到Windows Terminal Preview v0.11.1191.0后setting 的变化 (#58)




  
找到原因了，好像profile只能添加5个了，不知道是不是这个原因
  
我可以加 6 个啊？版本是 0.11.1121.0。

**Comment by Whale-fall** [comment]
21版本是可以安装6个的，我今天是在91版本的上测试的

**Comment by spencerwooo** [comment]
应该没限制 profile 个数吧，我文档里哪儿也没看到……（7 个也可以，刚试完），然后快捷键绑定文档里没提，就不管了吧，其实我一直用原来的快捷键，感觉也挺好的。就改一下 `theme` 那儿吧，如果你 PR 的话，在 `/dev` 目录下改就好 (‾◡◝)

**Comment by Whale-fall** [comment]
是我傻了，{}前有个,我没有加上去，直接在末尾添加的。
