### ISSUE TITLE
关于 WSL 默认 Shell 的配置

### ISSUE THREAD

**Issue by printempw** [spencerwooo/dowww#6]
不推荐使用 `C:\Windows\System32\bash.exe` 进入 WSL 环境，因为它永远只会尝试启动默认 WSL 发行版中的 **bash shell**，即使你已经设置了其他默认 shell（参见 [#1](https://blogs.msdn.microsoft.com/commandline/2017/11/28/a-guide-to-invoking-wsl/), [#2](https://blessing.studio/wsl-guide/#6-4-%E5%A4%9A%E7%A7%8D%E8%BF%9B%E5%85%A5-WSL-%E7%9A%84%E6%96%B9%E5%BC%8F%E6%AF%94%E8%BE%83)），推荐使用 `C:\Windows\System32\wsl.exe`。
  
同样地，应该使用 `chsh` 设置默认 shell 为 zsh，并使用 `wsl.exe` 进入 WSL 环境（这会启动默认发行版中的默认 shell），而非对 `~/.bashrc` 进行修改。此条目涉及的文章段落：

- https://github.com/spencerwooo/dowww/blob/master/docs/2-Toolchain/2-1-TerminalEnv.md#%E9%85%8D%E7%BD%AE-hyper-%E7%BB%88%E7%AB%AF
- https://github.com/spencerwooo/dowww/blob/master/docs/3-VSCode/3-0-Terminal.md#%E9%85%8D%E7%BD%AE

另外，关于 WSL 中 `ls` 命令输出的颜色问题，除了修改 `LS_COLORS` 外，其实还有另一种更治本一些的方法，参见：[DrvFs 文件权限问题](https://blessing.studio/wsl-guide/#6-6-DrvFs-%E6%96%87%E4%BB%B6%E6%9D%83%E9%99%90%E9%97%AE%E9%A2%98)。刚才在 V2EX 上看到了你的这个项目，正好之前我也写过一篇 WSL 相关的文章，所以斗胆提一些建议。;)

**Comment by spencerwooo** [comment]
感谢反馈！！！这几个建议都很有价值，我自己测试一下之后就更新，再次谢谢您。🎉🎉🎉

**Comment by spencerwooo** [comment]
我在这个模块[“终端环境”](https://spencerwoo.com/dowww/2-Toolchain/2-1-TerminalEnv.html#%E9%85%8D%E7%BD%AE-hyper-%E7%BB%88%E7%AB%AF)和这个模块[“VSCode 内置终端”](https://spencerwoo.com/dowww/3-VSCode/3-0-Terminal.html#%E9%85%8D%E7%BD%AE) 把配置部分改成了 `wsl.exe`；把这个部分[“背景颜色问题”](https://spencerwoo.com/dowww/2-Toolchain/2-1-TerminalEnv.html#%E8%A7%A3%E5%86%B3-ls-%E5%92%8C-cd-%E5%91%BD%E4%BB%A4%E5%90%8E%E8%83%8C%E6%99%AF%E8%89%B2%E9%97%AE%E9%A2%98)添加了对文件系统的说明，引用了您的那篇文章的部分内容，也标识了相应的内容出处，如果没什么问题的话我就把这个 Issue 关掉啦，再次谢谢您~

**Comment by printempw** [comment]
好的，也谢谢你采纳我的建议~
