### ISSUE TITLE
WSL调用Makefile支持

### ISSUE THREAD

**Issue by c4dr01d** [spencerwooo/dowww#7]
💡 **一个新的 Idea！**
教程里讲怎么在VSCode里调用WSL端的make，autoconf，automake，configure，cmake等构建工具，这个什么时候可以更新一下？

**Comment by spencerwooo** [comment]
这个不是在终端执行命令就可以吗，那么在 VSCode 内嵌终端执行理论上就可以吧……我并不会这个我只会 IDE 点点点...

**Comment by c4dr01d** [comment]
这个可以在tasks.json里面配置的，你研究一下？

**Comment by spencerwooo** [comment]
真不会这个啦！大佬会的话欢迎 PR

**Comment by c4dr01d** [comment]
我也不会啊，要不然也不会在这里提issue了啊

**Comment by spencerwooo** [comment]
我给 issue 标个 tag，等有缘人看到然后提 PR！哈哈哈

**Comment by c4dr01d** [comment]
可以，真皮，蛤蛤蛤蛤蛤蛤

**Comment by suyanhanx** [comment]
https://github.com/Microsoft/vscode/issues/22317

嗯？

**Comment by spencerwooo** [comment]
@suyanhanx 这个只是如何将 WSL 环境配置为默认的 VSCode 内置终端，另一位同学的意思是怎么写 `tasks.json` 和 `launch.json` 来直接 makefile 编译生成吧？这个我就不知道了

**Comment by spencerwooo** [comment]
Stale, closed.
