### ISSUE TITLE
<主机名>.mshome.net 访问主机

### ISSUE THREAD

**Issue by implic** [spencerwooo/dowww#73]
💡 **一个新的 Idea！**

发现我的 WSL 2 中可以用 <主机名>.mshome.net 访问 Windows 主机，但是未见到官方文档说明，不知道是否通用。

**Comment by spencerwooo** [comment]
诶好像还真的可以？

![image](https://user-images.githubusercontent.com/32114380/92296641-5e3ecd00-ef69-11ea-9d9e-4a2f3d09e587.png)

怎么发现的呢？这种 undocumented 的内容不知道靠不靠谱啊。

**Comment by spencerwooo** [comment]
@implic 在 WSL 2 里面可以看到 `x1carbon.mshome.net` 确实解析到 WSL 容器对应的 IP 地址了：

![image](https://user-images.githubusercontent.com/32114380/93204735-2b76af00-f789-11ea-879f-ba43e9e0fb39.png)

所以你具体是怎么发现这个的呢？我如果写到文档里面的话，这种半 hack 的方法应该至少加一个来源……

**Comment by implic** [comment]
啊是 nmap 扫描端口的时候它显示的 rDNS

似乎是 Hyper-V 有个 Internet Connection Sharing 的功能，会自动创建一个 hosts.ics 文件所以能解析。在 WSL 的 issues 问了一下是否官方支持，不过还没人回复😶

**Comment by spencerwooo** [comment]
@implic OK，了解了...（拿 `nmap` 扫自己机器端口可还行）

**Comment by implic** [comment]
因为这个 WSL 的网络被标记成公用的，某些程序开放给公共网络访问感觉不太安全，就创建了点防火墙规则，用 nmap 验证一下
