### ISSUE TITLE
ls背景色问题

### ISSUE THREAD

**Issue by Whale-fall** [spencerwooo/dowww#74]
昨天我的windows更新后,不知道为啥ls时又出现了背景色,如下:
![Snipaste_2020-09-06_22-31-15](https://user-images.githubusercontent.com/22662209/92328051-bae8d780-f090-11ea-9a63-4455967213f1.png)
.zshrc中有过配置
`# Change ls colours
    LS_COLORS="ow=01;36;40" && export LS_COLORS
#make cd use the ls colours
    zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"`

对wsl.conf和fstab也做了如下配置:

`[automount]
enabled = true
root = /mnt/
options = "metadata,umask=22,fmask=111"
mountFsTab = true`

`LABEL=cloudimg-rootfs   /        ext4   defaults        0 0
C: /mnt/d drvfs rw,noatime,uid=1000,gid=1000
D: /mnt/d drvfs rw,noatime,uid=1000,gid=1000,umask=22,fmask=111,metadata
E: /mnt/d drvfs rw,noatime,uid=1000,gid=1000,umask=22,fmask=111,metadata`

在D盘和E盘中没有出现这个问题,是更新引起的微小改动么?

wsl版本:
Linux LAPTOP-4Q7KJ49G 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
windows版本:
![Snipaste_2020-09-06_22-37-58](https://user-images.githubusercontent.com/22662209/92328219-a8bb6900-f091-11ea-896b-2b667424f288.png)

**Comment by Whale-fall** [comment]
不只是windows端,在wsl端某些目录也出现了背景色问题

**Comment by spencerwooo** [comment]
额，这个确实没遇到过，我也是 WSL 2，Windows 10 2004，但是目前我没有这个问题（无论是 Windows 路径下还是 Linux 路径下）。

![image](https://user-images.githubusercontent.com/32114380/92328462-96dac580-f093-11ea-8c36-9b2af53b32f9.png)

**Comment by Whale-fall** [comment]
重装了换用Ubuntu20.04后问题依然存在,不能确定是哪里出了问题,不知道其他更新过的人有没有也遇到这样的问题

**Comment by York618** [comment]
你是在用windows terminal吗
试下在cmd里面键入wsl之类
