### ISSUE TITLE
请教WSL安装arch后使用xfce桌面的问题

### ISSUE THREAD

**Issue by guohoo** [spencerwooo/dowww#76]
本人Linux新手，看到文档里面说有社区支持的arch可以安装，用LxRunOffline装上了，但是遇到了一些问题

1. `X server`跑不起来
安装了`xorg`和`xfce4`，但是使用`startxfce4`时会报错，`/var/log/Xorg.0.log`输出如下
```
# cat /var/log/Xorg.0.log|grep EE
[    37.337] (EE) dbus-core: error connecting to system bus: org.freedesktop.DBus.Error.FileNotFound (Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory)
[    37.617] (EE) open /dev/dri/card0: No such file or directory
[    37.620] (EE) open /dev/fb0: No such file or directory
[    37.620] (EE) open /dev/dri/card0: No such file or directory
[    37.621] (EE) open /dev/fb0: No such file or directory
[    37.621] (EE) No devices detected.
[    37.621] (EE)
[    37.621] (EE) no screens found(EE)
[    37.622] (EE)
[    37.622] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[    37.622] (EE)
[    37.623] (EE) Server terminated with error (1). Closing log file.
```
PS：用Ubuntu并没有出现以上的问题，看了一下作者那边已经有人提过，但好像并没有解决，所以来这里问问原因，还望各位不吝赐教，万分感激！

2. `.bashrc`文件并没有生效
alias设置和一些环境变量写进了用户目录下的`.bashrc`文件，但配置并没有生效。

新手上路，有很多东西也还不清楚，如描述有谬误，还望见谅

**Comment by spencerwooo** [comment]
1. WSL 2 的话可能需要修改一下 `DISPLAY` 环境变量的内容（写入 `.bashrc` 或者 `.zshrc`）：
  ```bash
  export DISPLAY="`grep nameserver /etc/resolv.conf | sed 's/nameserver //'`:0"
  ```  
  因为 WSL 2 有自己的 IP 地址，不这样设置 X Server 就没办法找到对应的 `DISPLAY`。我不确定这样能不能行，因为我其实并没有玩过 WSL GUI。另外微软马上要官方支持 WSL 的 GUI 显示了，就不必用这种 X Server 的方法了（详见：[Update on running Linux GUI apps in WSL](https://devblogs.microsoft.com/commandline/whats-new-in-the-windows-subsystem-for-linux-september-2020/#gui-apps)）。

2. 手动 `source ~/.bashrc` 也不好用吗？

**Comment by spencerwooo** [comment]
另外 Arch WSL 有社区支持：https://github.com/yuk7/ArchWSL，不必还用 LxRunOffline 自己搞吧？

**Comment by guohoo** [comment]
> 1. WSL 2 的话可能需要修改一下  环境变量的内容（写入  或者 ）：`DISPLAY``.bashrc``.zshrc`
>    ```shell
>    export DISPLAY="`grep nameserver /etc/resolv.conf | sed 's/nameserver //'`:0"
>    ```
>    
>    
>    因为 WSL 2 有自己的 IP 地址，不这样设置 X Server 就没办法找到对应的 。我不确定这样能不能行，因为我其实并没有玩过 WSL GUI。另外微软马上要官方支持 WSL 的 GUI 显示了，就不必用这种 X Server 的方法了（详见：[Update on running Linux GUI apps in WSL](https://devblogs.microsoft.com/commandline/whats-new-in-the-windows-subsystem-for-linux-september-2020/#gui-apps)）。`DISPLAY`
> 2. 手动  也不好用吗？`source ~/.bashrc`

谢谢大佬的回复，手动`source`只能在这次登录的终端有效，退出后又变回老样子了，需要重新`source`一次，很奇怪。
另外设置了环境变量一开始是可以run的，但是尝试在GUI登录时还是有错误
```
Failed to connect to bus: No such file or directory
dbus-update-activation-environment: error: unable to connect to D-Bus: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
```
感觉wsl用GUI还是坑有点多

**Comment by guohoo** [comment]
把`.bashrc`的内容写进`/etc/profile`反而能用，用户目录下的配置登录进去是没读取的

**Comment by spencerwooo** [comment]
> 把 `.bashrc` 的内容写进 `/etc/profile` 反而能用，用户目录下的配置登录进去是没读取的

https://askubuntu.com/questions/161249/bashrc-not-executed-when-opening-new-terminal

```bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
```

重点在于这部分，如果在你的 `~/.profile` 里面包含这个代码，那么 bash 登录之后根据 `~/.profile` 会加载 `~/.bashrc` 中的内容的。@guohoo

**Comment by guohoo** [comment]
受教了，十分感谢
