### ISSUE TITLE
找不到 python-pip 包 Unable to locate package python-pip

### ISSUE THREAD

**Issue by s-xiaoxiao** [spencerwooo/dowww#77]
**我在这个页面的配置过程遇到了问题：[安装python-pip](https://dowww.spencerwoo.com/3-vscode/3-3-python.html#%E5%AE%89%E8%A3%85-vs-code-%E6%8F%92%E4%BB%B6)**

```bash
➜  ~ sudo apt install python-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-pip
```

解决：
`sudo apt install python3-pip`

**Comment by spencerwooo** [comment]
Updated in the newest version of the documentation.
