### ISSUE TITLE
wsl无法唤起vscode

### ISSUE THREAD

**Issue by Whale-fall** [spencerwooo/dowww#8]
🤔 **我在这个页面的配置过程遇到了问题！**
在配置vscode的那一章的python配置章节，我不是很理解在wsl侧输入code&唤起vscode是什么意思，是唤起在wsl中安装的vscode还是唤起在安装在win10中的vscode呢。

> 详细说说你在配置哪一部分遇到了问题，有页面链接更好啦！
![snipaste_2018-11-29_16-51-31](https://user-images.githubusercontent.com/22662209/49210117-336c3000-f3f7-11e8-90d9-fa7703c96b17.png)
这个是在wsl端输入的
![snipaste_2018-11-29_16-50-32](https://user-images.githubusercontent.com/22662209/49210140-45e66980-f3f7-11e8-8c02-7a6ab4d601fd.png)
这个是系统的环境变量
![snipaste_2018-11-29_16-54-32](https://user-images.githubusercontent.com/22662209/49210198-77f7cb80-f3f7-11e8-84b3-ad2a473ca47b.png)
这个是fstab文件，这么做能排除C盘的挂载方式么，，以及现在彻底删除了wsl侧的vscode
🎉 **我觉得这里可以这样改进！**

> 附上链接，我即刻更新！

💡 **一个新的 Idea！**

> 详细讲讲，可以直接 PR！欢迎欢迎！

**Comment by spencerwooo** [comment]
1. Python 那一章节的需要这样唤起 VSCode 主要是由于我自己尝试，如果不这样唤起 VSCode 去编辑那个 `python.bat` 会出现一些莫名其妙的问题。只有这样操作一波才能让 VSCode 的 Python 插件识别到 WSL 侧的工具链
2. 关于无法唤起，可能还是环境变量的问题：

![image](https://user-images.githubusercontent.com/32114380/49210829-04ef5480-f3f9-11e8-960d-5ccc73f5bd9c.png)

可以按照这个方式再尝试一下能不能用 `code .` 唤起，理论上应该就是可以的了。

**Comment by Whale-fall** [comment]
但是显示的是No command matching啊，是版本更新的缘故么

**Comment by spencerwooo** [comment]
实在不行你可以重新安装最新的 VSCode 版本，然后在安装过程勾选「将 Code 添加到 `PATH`」，试试。

**Comment by Whale-fall** [comment]
好的呢，我尝试一下昂

**Comment by Whale-fall** [comment]
我过来反馈了，我尝试过重装了vscode，并在安装时将4个其他选项都勾选了，但是vscode重装后仍然沿用了之前的配置，所以我依然没有办法在wsl中唤起vscode，以及大佬你给出的方法2之所以提示No command matching是因为在win下是默认添加了环境变量，所以没有办法再添加一次。我想到的一个可能的方法是让wsl和win共用环境变量，参见：https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/
但是我现在还没有成功，成功了的话再过来反馈。

**Comment by Whale-fall** [comment]
alias code=""/mnt/c/Program Files (x86)/Microsoft VS Code/Code.exe""
in ~/.bashrc
我也看到有人这么建议，，但是这种和大佬你那种唤起方式有很大区别么

**Comment by spencerwooo** [comment]
啊呀。。。难受

理论上，在安装 VSCode 的时候，Add `code` to PATH，就可以将 code 添加到环境变量了。并且 WSL 和 Windows 环境变量是相通的。我也不知道你这个问题出在哪里了。

对了，PowerShell 里面 code 能用吗？能直接唤起 VSCode 吗？

**Comment by Whale-fall** [comment]
powershell里的可以唤起，，但是在wsl中不能。

**Comment by spencerwooo** [comment]
绝了...要不重装一下 WSL？

**Comment by Whale-fall** [comment]
啊那之前所有的配置会不会都会消失啊哭唧唧，可能真的是我安装的时候就出了问题吧，就很奇怪我一安装的时候，就显示的是root用户

**Comment by spencerwooo** [comment]
直接进 root? 那应该是安装过程出现问题了，因为会有一个步骤让你配置一个 Linux 账户和密码，可以考虑重装了...

**Comment by Whale-fall** [comment]
好的，我现在重装下

**Comment by Whale-fall** [comment]
我过来反馈了，还是不行，现在疯狂折腾中，救救孩子！

**Comment by Whale-fall** [comment]
我知道为什么了，因为我在oh-my-zsh里的plugins加了vscode，后面查了一下这个和ide似乎没有关系，所以code的别名被改变了，当然怎么输入code都没有用，打扰了。

**Comment by spencerwooo** [comment]
这...好的 解决了就好（我都不知道 oh-my-zsh 还有 VSCode 插件 🤦‍♂️）

**Comment by Whale-fall** [comment]
再次更新，可以在/etc/fstab中做如下配置可以有效解决wsl下不能访问win的应用程序的问题：
C: /mnt/c drvfs rw,noatime,uid=1000,gid=1000
